services:
  app:
    extends:
      file: compose.test.yml
      service: app
    environment:
      PHX_HOST: localhost
      PORT: 4000
      SECRET_KEY_BASE: "VlPUd2fbnWjh6Di+7SGc2SSXpNhI0hN766FFAlct65wU5ARyiGvK9r3TqSqKyu0K"
      GUARDIAN_SECRET_KEY: "VlPUd2fbnWjh6Di+7SGc2SSXpNhI0hN766FFAlct65wU5ARyiGvK9r3TqSqKyu0K"
      DATABASE_PATH: /config/mydia.db
      MIX_ENV: prod
      METADATA_RELAY_URL: ${METADATA_RELAY_URL:-https://metadata-relay.arsfeld.dev}

      # OIDC configuration for testing
      OIDC_ENABLED: "true"
      OIDC_ISSUER: "http://mock-oauth2:8080/default"
      OIDC_CLIENT_ID: "mydia"
      OIDC_CLIENT_SECRET: "secret"
      OIDC_SCOPES: "openid profile email"

      # Mock service URLs for E2E testing
      PROWLARR_URL: "http://mock-prowlarr:9696"
      PROWLARR_API_KEY: "test-api-key"
      QBITTORRENT_URL: "http://mock-qbittorrent:8080"
      QBITTORRENT_USERNAME: "admin"
      QBITTORRENT_PASSWORD: "adminpass"
    depends_on:
      mock-prowlarr:
        condition: service_healthy
      mock-qbittorrent:
        condition: service_healthy
      mock-oauth2:
        condition: service_started

  mock-oauth2:
    extends:
      file: compose.test.yml
      service: mock-oauth2

  mock-prowlarr:
    build:
      context: ./test/mock_services/prowlarr
      dockerfile: Dockerfile
    container_name: mydia_mock_prowlarr
    ports:
      - "19696:9696"
    environment:
      PORT: 9696
      API_KEY: "test-api-key"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:9696/health",
        ]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 3

  mock-qbittorrent:
    build:
      context: ./test/mock_services/qbittorrent
      dockerfile: Dockerfile
    container_name: mydia_mock_qbittorrent
    ports:
      - "8082:8080"
    environment:
      PORT: 8080
      USERNAME: "admin"
      PASSWORD: "adminpass"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:8080/health",
        ]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 3

  playwright:
    extends:
      file: compose.test.yml
      service: playwright
    depends_on:
      app:
        condition: service_healthy
      mock-prowlarr:
        condition: service_healthy
      mock-qbittorrent:
        condition: service_healthy

volumes:
  test_config:
    driver: local
  test_data:
    driver: local
  test_media:
    driver: local
