services:
  app:
    image: mydia:test
    container_name: mydia_test
    environment:
      PHX_HOST: localhost
      PORT: 4000
      SECRET_KEY_BASE: "VlPUd2fbnWjh6Di+7SGc2SSXpNhI0hN766FFAlct65wU5ARyiGvK9r3TqSqKyu0K"
      GUARDIAN_SECRET_KEY: "VlPUd2fbnWjh6Di+7SGc2SSXpNhI0hN766FFAlct65wU5ARyiGvK9r3TqSqKyu0K"
      DATABASE_PATH: /config/mydia.db
      MIX_ENV: prod
      METADATA_RELAY_URL: ${METADATA_RELAY_URL:-https://metadata-relay.fly.dev}

      # OIDC configuration for testing
      OIDC_ENABLED: "true"
      OIDC_ISSUER: "http://mock-oauth2:8080/default"
      OIDC_CLIENT_ID: "mydia"
      OIDC_CLIENT_SECRET: "secret"
      OIDC_SCOPES: "openid profile email"
    ports:
      - "4000:4000"
    volumes:
      - test_config:/config
      - test_data:/data
      - test_media:/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3

  mock-oauth2:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    container_name: mydia_test_oauth
    ports:
      - "8080:8080"
    environment:
      JSON_CONFIG: |
        {
          "interactiveLogin": true,
          "httpServer": "NettyWrapper",
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 3600,
              "requestMappings": [
                {
                  "requestParam": "grant_type",
                  "match": "authorization_code",
                  "claims": {
                    "sub": "test-user",
                    "aud": ["mydia"],
                    "email": "test@example.com",
                    "name": "Test User"
                  }
                }
              ]
            }
          ]
        }

volumes:
  test_config:
    driver: local
  test_data:
    driver: local
  test_media:
    driver: local
