import Config

# Configure your database
config :mydia, Mydia.Repo,
  database: Path.expand("../mydia_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # SQLite-specific optimizations
  timeout: 5000,
  journal_mode: :wal,
  cache_size: -64000,  # 64MB cache
  temp_store: :memory,
  synchronous: :normal,
  foreign_keys: :on,
  busy_timeout: 5000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mydia, MydiaWeb.Endpoint,
  # Binding to all interfaces to allow access from Docker host
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "VlPUd2fbnWjh6Di+7SGc2SSXpNhI0hN766FFAlct65wU5ARyiGvK9r3TqSqKyu0K",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:mydia, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:mydia, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :mydia, MydiaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/mydia_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :mydia, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Guardian secret key for development (NOT for production!)
config :mydia, Mydia.Auth.Guardian,
  secret_key: "dev_secret_key_replace_in_production_with_secure_random_key"

# Ueberauth OIDC configuration for development
# These can be overridden with environment variables
oidc_issuer = System.get_env("OIDC_ISSUER")
oidc_client_id = System.get_env("OIDC_CLIENT_ID")
oidc_client_secret = System.get_env("OIDC_CLIENT_SECRET")

if oidc_issuer && oidc_client_id && oidc_client_secret do
  config :ueberauth, Ueberauth.Strategy.Oidcc,
    issuer: oidc_issuer,
    client_id: oidc_client_id,
    client_secret: oidc_client_secret,
    redirect_uri: System.get_env("OIDC_REDIRECT_URI") || "http://localhost:4000/auth/oidc/callback",
    scopes: System.get_env("OIDC_SCOPES") || "openid profile email"

  config :ueberauth, Ueberauth,
    providers: [
      oidc: {Ueberauth.Strategy.Oidcc, []}
    ]
end
